# Generated by Django 4.0.4 on 2022-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imgurl',
            field=models.URLField(blank=True),
        ),
    ]
